In [1]:
import pandas as pd
import time

In [ ]:
print("Loading data... it may take a while depending on your machine's specs.")
start_time = time.time()
df = pd.read_csv("hotel_reviews.csv", nrows=515000)
end_time = time.time()
print(f"data loaded in {end_time - start_time} seconds")

Loading data... it may take a while depending on your machine's specs.
data loaded in 1.6032509803771973 seconds

In [23]:
df

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,52.360576,4.915968
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3 days,52.360576,4.915968
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10 days,52.360576,4.915968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514995,Wrights Lane Kensington and Chelsea London W8 ...,1172,3/24/2016,7.8,Holiday Inn London Kensington,United Kingdom,The staff and service was aweful,7,5945,No Positive,0,1,6.7,"[' Leisure trip ', ' Group ', ' Standard Twin ...",497 day,51.499981,-0.192879
514996,Wrights Lane Kensington and Chelsea London W8 ...,1172,3/24/2016,7.8,Holiday Inn London Kensington,United Kingdom,No Negative,0,5945,24h room service Excellent,6,2,10.0,"[' Business trip ', ' Family with young childr...",497 day,51.499981,-0.192879
514997,Wrights Lane Kensington and Chelsea London W8 ...,1172,3/24/2016,7.8,Holiday Inn London Kensington,Jersey,Everything else housekeeping woke us up 5 tim...,11,5945,The reception,3,1,2.5,"[' Leisure trip ', ' Group ', ' Standard Twin ...",497 day,51.499981,-0.192879
514998,Wrights Lane Kensington and Chelsea London W8 ...,1172,3/22/2016,7.8,Holiday Inn London Kensington,Greece,Room space width of bed bathroom shower I sli...,17,5945,Location and access to transportation,6,13,7.9,"[' Business trip ', ' Couple ', ' Standard Dou...",499 day,51.499981,-0.192879
514999,Wrights Lane Kensington and Chelsea London W8 ...,1172,3/22/2016,7.8,Holiday Inn London Kensington,United Kingdom,No Negative,0,5945,Easy to get to underground The staff where ve...,12,2,9.6,"[' Leisure trip ', ' Couple ', ' Executive Dou...",499 day,51.499981,-0.192879

In [ ]:
print(df.columns)

Index(['Hotel_Address', 'Additional_Number_of_Scoring', 'Review_Date',
       'Average_Score', 'Hotel_Name', 'Reviewer_Nationality',
       'Negative_Review', 'Review_Total_Negative_Word_Counts',
       'Total_Number_of_Reviews', 'Positive_Review',
       'Review_Total_Positive_Word_Counts',
       'Total_Number_of_Reviews_Reviewer_Has_Given', 'Reviewer_Score', 'Tags',
       'days_since_review', 'lat', 'lng'],
      dtype='object')

In [16]:
print(df.shape)

(515000, 17)

In [22]:
df
print(df["Reviewer_Nationality"].unique())
# print(df["Reviewer_Nationality"].value_counts())
print("most common nationality to review is:" , df["Reviewer_Nationality"].value_counts().idxmax() , "with" , df["Reviewer_Nationality"].value_counts().max() , "reviews")
print("The next 10 most common nationalities to review are:")
print(df["Reviewer_Nationality"].value_counts().nlargest(11).iloc[1:])

[' Russia ' ' Ireland ' ' Australia ' ' United Kingdom ' ' New Zealand '
 ' Poland ' ' Belgium ' ' Norway ' ' France ' ' Italy ' ' Canada '
 ' Netherlands ' ' Germany ' ' United States of America ' ' Hungary '
 ' Israel ' ' Switzerland ' ' India ' ' United Arab Emirates '
 ' Malaysia ' ' Denmark ' ' South Africa ' ' Rwanda ' ' Finland '
 ' Portugal ' ' Luxembourg ' ' Spain ' ' Malta ' ' China ' ' Turkey '
 ' Ukraine ' ' Gibraltar ' ' Argentina ' ' Abkhazia Georgia '
 ' Isle of Man ' ' Sweden ' ' Croatia ' ' Saudi Arabia ' ' Lithuania '
 ' Slovenia ' ' Panama ' ' Austria ' ' Brazil ' ' Taiwan ' ' Iceland '
 ' Iran ' ' Liechtenstein ' ' Chile ' ' Hong Kong '
 ' United States Minor Outlying Islands ' ' Morocco ' ' Oman ' ' Lebanon '
 ' Qatar ' ' Nigeria ' ' Romania ' ' Czech Republic ' ' Greece '
 ' Thailand ' ' Singapore ' ' Guernsey ' ' Latvia ' ' Namibia ' ' Japan '
 ' Egypt ' ' Slovakia ' ' South Korea ' ' Kuwait ' ' Bahrain ' ' Jersey '
 ' Jordan ' ' Bulgaria ' ' Cyprus ' ' Albania ' ' Estonia ' ' Serbia '
 ' Belarus ' ' Puerto Rico ' ' Sudan ' ' Sri Lanka ' ' Indonesia '
 ' Honduras ' ' Philippines ' ' Montenegro ' ' Uruguay ' ' Brunei '
 ' Pakistan ' ' Kosovo ' ' Azerbaijan ' ' ' ' Botswana ' ' Tanzania '
 ' Bangladesh ' ' Trinidad and Tobago ' ' Palestinian Territory ' ' Peru '
 ' Mexico ' ' Kenya ' ' Zimbabwe ' ' Macedonia ' ' Georgia ' ' Bermuda '
 ' Costa Rica ' ' Bahamas ' ' Maldives ' ' Barbados ' ' Libya ' ' Fiji '
 ' Angola ' ' Kazakhstan ' ' Bosnia and Herzegovina ' ' Colombia '
 ' Armenia ' ' Vietnam ' ' Iraq ' ' Monaco ' ' Uganda ' ' Togo '
 ' Guatemala ' ' Ghana ' ' Macau ' ' Zambia ' ' Jamaica ' ' Mauritius '
 ' Venezuela ' ' Crimea ' ' St Maarten ' ' Algeria ' ' Equatorial Guinea '
 ' Nicaragua ' ' Comoros ' ' Cayman Islands ' ' Ethiopia '
 ' Dominican Republic ' ' Ecuador ' ' Uzbekistan '
 ' Turks Caicos Islands ' ' Nepal ' ' Mozambique ' ' Sierra Leone '
 ' Ivory Coast ' ' Cura ao ' ' Antigua Barbuda ' ' Burundi '
 ' East Timor ' ' Tunisia ' ' Andorra ' ' U S Virgin Islands '
 ' Antarctica ' ' Papua New Guinea ' ' Montserrat ' ' Malawi ' ' Yemen '
 ' Suriname ' ' Paraguay ' ' Aruba ' ' Mongolia ' ' Moldova '
 ' St Pierre and Miquelon ' ' Cambodia ' ' Seychelles ' ' Guyana '
 ' Senegal ' ' El Salvador ' ' Guam ' ' Myanmar ' ' Madagascar ' ' Benin '
 ' Saint Kitts and Nevis ' ' Martinique ' ' Vanuatu '
 ' British Virgin Islands ' ' Belize '
 ' Democratic Republic of the Congo ' ' Gabon ' ' New Caledonia '
 ' Bhutan ' ' Faroe Islands ' ' Kyrgyzstan ' ' Gambia ' ' Syria ' ' Laos '
 ' Mauritania ' ' Central Africa Republic ' ' Reunion ' ' Saint Martin '
 ' Cameroon ' ' Guadeloupe ' ' Liberia ' ' Haiti ' ' Mali '
 ' Saint Lucia ' ' French Guiana ' ' Swaziland '
 ' Falkland Islands Malvinas ' ' Tajikistan ' ' Afghanistan ' ' Bolivia '
 ' Dominica ' ' Niger ' ' Samoa ' ' Lesotho ' ' French Polynesia '
 ' Grenada ' ' Wallis and Futuna ' ' Svalbard Jan Mayen ' ' Djibouti '
 ' Saint Barts ' ' Kiribati ' ' Cook Islands ' ' Congo ' ' Somalia '
 ' Eritrea ' ' Saint Vincent Grenadines ' ' San Marino ' ' Turkmenistan '
 ' Vatican City ' ' South Sudan ' ' Anguilla ' ' Cocos K I '
 ' Bonaire St Eustatius and Saba ' ' Cape Verde '
 ' Northern Mariana Islands ' ' Tuvalu ' ' Guinea ' ' American Samoa '
 ' Palau ']
most common nationality to review is:  United Kingdom  with 244928 reviews
The next 10 most common nationalities to review are:
Reviewer_Nationality
United States of America     35408
Australia                    21669
Ireland                      14796
United Arab Emirates         10218
Saudi Arabia                  8943
Netherlands                   8760
Switzerland                   8665
Germany                       7933
Canada                        7888
France                        7291
Name: count, dtype: int64

In [26]:
top_nationalities = df["Reviewer_Nationality"].value_counts().head(10).index

for nationality in top_nationalities:
    subset = df[df["Reviewer_Nationality"] == nationality]
    hotel_counts = subset["Hotel_Name"].value_counts()
    top_hotel = hotel_counts.idxmax()
    top_count = hotel_counts.max()
    print(f"{nationality}: {top_hotel} ({top_count} reviews)")

 United Kingdom : Britannia International Hotel Canary Wharf (3833 reviews)
 United States of America : Hotel Esther a (423 reviews)
 Australia : Park Plaza Westminster Bridge London (167 reviews)
 Ireland : Copthorne Tara Hotel London Kensington (239 reviews)
 United Arab Emirates : Millennium Hotel London Knightsbridge (129 reviews)
 Saudi Arabia : The Cumberland A Guoman Hotel (142 reviews)
 Netherlands : Jaz Amsterdam (97 reviews)
 Switzerland : Hotel Da Vinci (97 reviews)
 Germany : Hotel Da Vinci (86 reviews)
 Canada : St James Court A Taj Hotel London (61 reviews)

In [27]:
# First create a new dataframe based on the old one, removing the uneeded columns
hotel_freq_df = df.drop(["Hotel_Address", "Additional_Number_of_Scoring", "Review_Date", "Average_Score", "Reviewer_Nationality", "Negative_Review", "Review_Total_Negative_Word_Counts", "Positive_Review", "Review_Total_Positive_Word_Counts", "Total_Number_of_Reviews_Reviewer_Has_Given", "Reviewer_Score", "Tags", "days_since_review", "lat", "lng"], axis = 1)

# Group the rows by Hotel_Name, count them and put the result in a new column Total_Reviews_Found
hotel_freq_df['Total_Reviews_Found'] = hotel_freq_df.groupby('Hotel_Name').transform('count')

# Get rid of all the duplicated rows
hotel_freq_df = hotel_freq_df.drop_duplicates(subset = ["Hotel_Name"])
display(hotel_freq_df)

,Hotel_Name,Total_Number_of_Reviews,Total_Reviews_Found
0,Hotel Arena,1403,405
405,K K Hotel George,1831,566
971,Apex Temple Court Hotel,2619,1037
2008,The Park Grand London Paddington,4380,1770
3778,Monhotel Lounge SPA,171,35
...,...,...,...
511920,Das Triest Hotel,275,42
511962,Suite Hotel 900 m zur Oper,3461,439
512401,Hotel Amadeus,717,144
512545,The Berkeley,232,100
512645,Holiday Inn London Kensington,5945,2355

In [29]:
# define a function that takes a row and performs some calculation with it
def get_difference_review_avg(row):
  return row["Average_Score"] - row["Calc_Average_Score"]

# 'mean' is mathematical word for 'average'
df['Calc_Average_Score'] = round(df.groupby('Hotel_Name').Reviewer_Score.transform('mean'), 1)

# Add a new column with the difference between the two average scores
df["Average_Score_Difference"] = df.apply(get_difference_review_avg, axis = 1)

# Create a df without all the duplicates of Hotel_Name (so only 1 row per hotel)
review_scores_df = df.drop_duplicates(subset = ["Hotel_Name"])

# Sort the dataframe to find the lowest and highest average score difference
review_scores_df = review_scores_df.sort_values(by=["Average_Score_Difference"])

display(review_scores_df[["Average_Score_Difference", "Average_Score", "Calc_Average_Score", "Hotel_Name"]])

,Average_Score_Difference,Average_Score,Calc_Average_Score,Hotel_Name
495945,-0.8,7.7,8.5,Best Western Hotel Astoria
111027,-0.7,8.8,9.5,Hotel Stendhal Place Vend me Paris MGallery by...
43688,-0.7,7.5,8.2,Mercure Paris Porte d Orleans
178253,-0.7,7.9,8.6,Renaissance Paris Vendome Hotel
218258,-0.5,7.0,7.5,Hotel Royal Elys es
...,...,...,...,...
478361,0.7,8.4,7.7,Hotel La Spezia Gruppo MiniHotel
22189,0.8,7.1,6.3,Holiday Inn Paris Montparnasse Pasteur
68936,0.9,6.8,5.9,Villa Eugenie
250308,0.9,8.6,7.7,MARQUIS Faubourg St Honor Relais Ch teaux
3813,1.3,7.2,5.9,Kube Hotel Ice Bar

In [30]:
# with lambdas:
start = time.time()
no_negative_reviews = df.apply(lambda x: True if x['Negative_Review'] == "No Negative" else False , axis=1)
print("Number of No Negative reviews: " + str(len(no_negative_reviews[no_negative_reviews == True].index)))

no_positive_reviews = df.apply(lambda x: True if x['Positive_Review'] == "No Positive" else False , axis=1)
print("Number of No Positive reviews: " + str(len(no_positive_reviews[no_positive_reviews == True].index)))

both_no_reviews = df.apply(lambda x: True if x['Negative_Review'] == "No Negative" and x['Positive_Review'] == "No Positive" else False , axis=1)
print("Number of both No Negative and No Positive reviews: " + str(len(both_no_reviews[both_no_reviews == True].index)))
end = time.time()
print("Lambdas took " + str(round(end - start, 2)) + " seconds")

# without lambdas (using a mixture of notations to show you can use both)
start = time.time()
no_negative_reviews = sum(df.Negative_Review == "No Negative")
print("Number of No Negative reviews: " + str(no_negative_reviews))

no_positive_reviews = sum(df["Positive_Review"] == "No Positive")
print("Number of No Positive reviews: " + str(no_positive_reviews))

both_no_reviews = sum((df.Negative_Review == "No Negative") & (df.Positive_Review == "No Positive"))
print("Number of both No Negative and No Positive reviews: " + str(both_no_reviews))

end = time.time()
print("Sum took " + str(round(end - start, 2)) + " seconds")

Number of No Negative reviews: 127738
Number of No Positive reviews: 35845
Number of both No Negative and No Positive reviews: 127
Lambdas took 5.07 seconds
Number of No Negative reviews: 127738
Number of No Positive reviews: 35845
Number of both No Negative and No Positive reviews: 127
Sum took 0.13 seconds